# Site settings
author: Anthony Mai
title: Learning to Code
header-img: img/home-bg.png
email: anthony.mai530@gmail.com
copyright_name: Anthony Mai
description: > # this means to ignore newlines until "baseurl:"
  Online Coding Course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  antimonysayz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
